[package]
name = "pikeyboard"
version = "0.1.0"
authors = ["Black616Angel <the-black-angel@gmx.de>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
